[general]
live_config_reload = true

[window]
decorations = "None"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 0
y = 0

[font]
size = 11.0
builtin_box_drawing = false

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[cursor]
style = "Beam"
unfocused_hollow = true

[colors.primary]
background = "0x060606"
foreground = "0xE6E6E6"

[colors.normal]
black = "0x000000"
red = "0xFF4141"
green = "0x37D67A"
yellow = "0xF2E85A"
blue = "0x3A7AFE"
magenta = "0xC839FF"
cyan = "0x3DF3FF"
white = "0xD0D0D0"

[colors.bright]
black = "0x555555"
red = "0xFF6B6B"
green = "0x52F99A"
yellow = "0xFFF56D"
blue = "0x5A92FF"
magenta = "0xD97FFF"
cyan = "0x82FCFF"
white = "0xFFFFFF"


